name: Main Taski Workflow
on:
  push:
    branches:
      - main
jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check ot repository code
      uses: actions/checkout@v3
      - name: PRing project tree
      run: tree .
